//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ClinicForAnimal1._2
{
    public partial class AppointmentDiary
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int SomeImportantKey { get; set; }
        public DateTime DateTimeScheduled { get; set; }
        public int AppointmentLength { get; set; }
        public int StatusEnum { get; set; }
    }
}
