//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicForAnimal1._2
{
    using System.Data.Entity;

    public partial class CalendarContext : DbContext
    {
        public CalendarContext()
            : base("name=CalendarContext")
        {
        }
  
        public virtual DbSet<AppointmentDiary> AppointmentDiaries { get; set; }
    }
}
