//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicForAnimal1._2.Models.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeterinarianService
    {
        public int Id { get; set; }
        public string NameOfVeterinaryServices { get; set; }
        public string UnitOfMeasurement { get; set; }
        public int Cost { get; set; }
        public string Category { get; set; }
    }
}
