//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicForAnimal1._2.Models.Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerServices : DbContext
    {
        public VerServices()
            : base("name=VerServices")
        {
        }
    
        public virtual DbSet<VeterinarianService> VeterinarianServices { get; set; }
    }
}
